/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>

#define RCC_BASE 			0x40023800UL

#define CLK_CTRL			0x00UL
#define HSEBYP				(1 << 18)
#define HSEON				(1 << 16)

#define CLK_CFGR			0x08UL
#define HSE_SYSCLK			(1 << 0)
#define HSE_MCO1			(2 << 21)
#define SYSCLK_SWS			0x0000000CUL

#define CLK_AHB1ENR			0x30UL
#define GPIOAEN				(1 << 0)

/* RCC Registers */
#define RCC_CLK_CTRL_REG 	(RCC_BASE + CLK_CTRL)
#define RCC_CFGR_REG	 	(RCC_BASE + CLK_CFGR)
#define RCC_CLK_AHB1EN_REG	(RCC_BASE + CLK_AHB1ENR)

#define GPIOA_BASE			0x40020000UL
#define GPIO_MODE			0x0UL
#define GPIO_ALT_HIGH		0x24UL

/* GPIOA Registers */
#define GPIOA_MODE_REG		(GPIOA_BASE + GPIO_MODE)
#define GPIOA_ALT_HIGH_REG	(GPIOA_BASE + GPIO_ALT_HIGH)

int main(void)
{
	/* switch to HSE */
	uint32_t *pRccClkCtrl = (uint32_t*)RCC_CLK_CTRL_REG;
	*pRccClkCtrl |= HSEBYP;
	*pRccClkCtrl |= HSEON;

	/* once the HSE is ON, do we need to clear HSION bit? */

	/* switch on HSE bit for SYSCLK*/
	uint32_t *pRccClkCfg = (uint32_t*)RCC_CFGR_REG;
	*pRccClkCfg |= HSE_SYSCLK;
	*pRccClkCfg |= HSE_MCO1;

	/*As this is clock from other chip, no need to wait for system clock switch status bit to set.
	 * If HSE is from external crystal then need to wait for status bit to set. This is required to
	 * give settlement time.
	 **/

	/* Route HSE to MCO1 */
	//Enable GPIOA CLK; GPIOA engine turned on
	uint32_t *pRccClkGpioA = (uint32_t*)RCC_CLK_AHB1EN_REG;
	*pRccClkGpioA |= GPIOAEN;

	// set PA8 as ALT function
	uint32_t *pGpioAMode = (uint32_t*)GPIOA_MODE_REG;
	*pGpioAMode |= (2 << 16);

	// set alternate mode to 0 for PA8
	uint32_t *pGpioAAltHigh = (uint32_t*)GPIOA_ALT_HIGH_REG;
	*pGpioAAltHigh &= ~(0xf << 0);

	for(;;);
}
