/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>

#define ADC_BASE_ADDR 0x40012000UL  /* postfix UL: as address is always unsigned long  */
#define ADC_CR1_REG_OFFSET	0x04UL
#define ADC_CR1_REG_ADDR (ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)
#define SCANEN (1 << 8)

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB2ENR_OFFSET 0x44UL
#define RCC_APB2ENR_REG_ADDR (RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)
#define ADC1EN (1 << 8)


/* This program demonstrates setting peripheral control registers
 * without turning on the peripheral clock. First try commenting of enable of
 * ADC1 clock And then try to configure the register after turning on the peripheral
 * clock register.
 *
 **/

int main(void)
{
	uint32_t *pAdcCtr1Reg = (uint32_t*) ADC_CR1_REG_ADDR;

	uint32_t *pRccApb2EnrReg = (uint32_t*) RCC_APB2ENR_REG_ADDR;

	/* first enable the peripheral clock before accessing peripheral registers */
	*pRccApb2EnrReg |= ADC1EN;

	/* configure the peripheral register set 8th bit */
	*pAdcCtr1Reg |= SCANEN;


	for(;;);
}
